bda - getter function
ropensci/c14bazAAR pull request #127
Opened 2021-03-23 10:31 UTC by zoometh

first step to recover the ['bda' C14 database ](https://nakala.fr/10.34847/nkl.dde9fnm8)

added values/complete the files:

  - url_references.csv
  - variable_reference.csv
  - material_thesaurus.csv
  - country_thesaurus.csv

added 'bda' to get_c14data()

2021-03-23 11:38 UTC, dirkseidensticker commented
@zoometh what a great starting point. I do not know how far you are to write the actual parser, but maybe you want to consider to have a look a the [parser for the euroevol database](https://github.com/ropensci/c14bazAAR/blob/master/R/get_euroevol.R). This database is also based on multiple individual files that need to be joined. 

If you need any assistance, I am there as well. Many thanks for your contribution already 👍

2021-03-23 17:07 UTC, zoometh commented
@dirkseidensticker Yes I've started to write the `get_bda()` function inspired by the `get_euroevol()` function. I guess the `get_bda()` function will be ready within a week. If I have some issues, I'll let you know.

2021-03-28 19:49 UTC, zoometh commented
@dirkseidensticker I've finally created the `get_bda` function. The joins between the 3 unzipped `.xlsx` files (Dates, Sites, Occupations) works but I was unable to check it with the c14bazAAR package since the `url_references.csv` file appears to be removed (temporally) from the package, maybe because of my previous commit.. This is the first time I used branches, and my skills with GitHub are still basics. Whatever, I can still help out.

2021-03-29 08:44 UTC, dirkseidensticker commented
@zoometh we made some changes within #128 and the latest [v2 release](https://github.com/ropensci/c14bazAAR/tree/2.0.0). We removed the url table which one had to update on the remote. Could you pull the changes and add your url's to the new [db_info_table.csv](https://github.com/ropensci/c14bazAAR/blob/master/data-raw/db_info_table.csv) table? `get_db_url("[the database name]")` refers now to this table.

Removing the odd `url_references.csv` reference was something we wanted to do for some time, sorry that it intervened with your PR.

2021-03-29 12:09 UTC, zoometh commented
I've just added a line in `db_info_table.csv` to register the `bda` database, [here](https://github.com/ropensci/c14bazAAR/pull/130/commits/8a452d783b813c35951fe9337d35a395f770cb74)

2021-04-01 11:22 UTC, dirkseidensticker commented on R/get_bda.R
> +  unzip(temp, files="BDA-Table_Dates.xlsx", exdir=td, overwrite=TRUE)
add `utils::unzip(...`

2021-04-01 11:22 UTC, dirkseidensticker commented on R/get_bda.R
> +  unzip(temp, files="BDA-Table_Occupations.xlsx", exdir=td, overwrite=TRUE)
add `utils::unzip(...`

2021-04-01 11:22 UTC, dirkseidensticker commented on R/get_bda.R
> +  unzip(temp, files="BDA-Table_Sites.xlsx", exdir=td, overwrite=TRUE)
add `utils::unzip(...`

2021-04-01 11:23 UTC, dirkseidensticker commented on R/get_bda.R
> +
add 
```r
names(c14dates) <- gsub("\u00E9", "e", names(c14dates))
names(c14occupa) <- gsub("\u00E9", "e", names(c14occupa))
names(c14sites) <- gsub("\u00E9", "e", names(c14sites))
```
in order to replace non-ascii characters

2021-04-01 11:23 UTC, dirkseidensticker commented on R/get_bda.R
> +      method = .data[["Méthode"]],
change `"Méthode"` into `"Methode"`

2021-04-01 11:24 UTC, dirkseidensticker commented on R/get_bda.R
> +      period = .data[["période"]],
change `"période"` into `""periode"`

2021-04-01 11:25 UTC, dirkseidensticker commented on R/get_bda.R
> +      material = .data[["Matériel_daté"]],
change `"Matériel_daté"` into `"Matèriel_date"

2021-04-01 11:25 UTC, dirkseidensticker commented on R/get_bda.R
> +      species = .data[["Matériel_daté_précision"]],
change `"Matériel_daté_précision"` into `"Materiel_date_precision"`

2021-04-01 11:26 UTC, dirkseidensticker commented on R/get_bda.R
> +      region = .data[["Région"]],
change `"Région"`into `"Region"`

2021-04-01 11:26 UTC, dirkseidensticker commented on R/get_bda.R
> +      comment = .data[["Fiabilité.x"]],
change `"Fiabilité.x"` into `"Fiabilite.x"`

2021-04-01 11:27 UTC, dirkseidensticker commented on R/get_bda.R
> +    dplyr::left_join(c14sites, by = c("id_site_associé" = "id_sites")) %>%
change `"id_site_associé"` into `"id_site_associe"`

2021-04-01 11:27 UTC, dirkseidensticker commented on R/get_bda.R
> +    dplyr::left_join(c14occupa, by = c("id_occupation_liée" = "id_occupations_2019")) %>%
change `"id_occupation_liée"` into `"id_occupation_liee"`

2021-04-01 11:28 UTC, dirkseidensticker commented on data-raw/url_reference.csv
> +bda,2021-03-23,1,https://api.nakala.fr/data/10.34847/nkl.dde9fnm8/189e04d917ffd68352a389006f357b58efda855e
line should be removed, as it is solved with #130

2021-04-01 11:32 UTC, dirkseidensticker requested changes
dear @zoometh , please excuse the long waiting time. I checked you parser, which looks (nearly) perfect! Congratulations and many thanks for your efforts from @nevrome and myself.

While running the checks, I noticed that you kept the french "é" in the column header. While this does not trigger an error, it flags a warning. Could you replace those characters?

Also, I noticed that you PR #130 was a bit redundant. Just keep in mind that when you add the url to the reference table, you would need to perform a "Clean and Rebuild" (in RStudio within the "More" menue within the "Build" tab. That triggers that the helper indices, like `db_info_table` are build again. Maybe we should add this to the README? @nevrome what do you think?

2021-04-01 20:16 UTC, zoometh commented
Dear ***@***.****, ***@***.*** *I'm currently out of the office with
little access to the internet. Get back to work next Sunday (!). If that's
fine for you I will accomplish the required changes at this date. Let me
know,

On Thu, Apr 1, 2021 at 1:32 PM Dirk Seidensticker ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> dear @zoometh <https://github.com/zoometh> , please excuse the long
> waiting time. I checked you parser, which looks (nearly) perfect!
> Congratulations and many thanks for your efforts from @nevrome
> <https://github.com/nevrome> and myself.
>
> While running the checks, I noticed that you kept the french "é" in the
> column header. While this does not trigger an error, it flags a warning.
> Could you replace those characters?
>
> Also, I noticed that you PR #130
> <https://github.com/ropensci/c14bazAAR/pull/130> was a bit redundant.
> Just keep in mind that when you add the url to the reference table, you
> would need to perform a "Clean and Rebuild" (in RStudio within the "More"
> menue within the "Build" tab. That triggers that the helper indices, like
> db_info_table are build again. Maybe we should add this to the README?
> @nevrome <https://github.com/nevrome> what do you think?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ropensci/c14bazAAR/pull/127#pullrequestreview-626165778>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQGHHLTWWMKDALQTLVZHWADTGRKVFANCNFSM4ZU4RE3Q>
> .
>

2021-04-02 11:17 UTC, dirkseidensticker commented
> ... Just keep in mind that when you add the url to the reference table, you would need to perform a "Clean and Rebuild" (in RStudio within the "More" menue within the "Build" tab. That triggers that the helper indices, like `db_info_table` are build again. Maybe we should add this to the README? @nevrome what do you think?

I missed this one yesterday: you need to run `data-raw/data_prep.R` to integrate the url added to the reference table (see no8 in [Adding database getter functions](https://github.com/ropensci/c14bazAAR#adding-database-getter-functions)).

2021-04-03 14:23 UTC, nevrome commented
Yes - it's maybe a bit tricky that no5, 6 and 7 don't do anything without 8, but I didn't want to be redundant

2021-04-04 11:14 UTC, zoometh reviewed
I guess that's all fine. What will be the next step @dirkseidensticker ?

2021-04-04 16:22 UTC, closed without merging